version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  test-react:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          include-branch-in-cache-key: false
workflows:
  node-tests:
    jobs:
      - test-react
