version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  test-react:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
workflows:
  node-tests:
    jobs:
      - test-react